name: Adding zones to DNS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Sync fork
      uses: TG908/fork-sync@v1.1
      with:
        github_token: ${{ secrets.repo_token }}
        owner: nightwatch92
        base: master
        head: master 
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r scripts/requirements.txt
